<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'CmsGeo\Factory\View\Helper\HierarchyHelperFactory' => __DIR__ . '/src/Factory/View/Helper/HierarchyHelperFactory.php',
    'CmsGeo\Mapping\GroupInterface'                     => __DIR__ . '/src/Mapping/GroupInterface.php',
    'CmsGeo\Mapping\Subdivision\LocalityInterface'      => __DIR__ . '/src/Mapping/Subdivision/LocalityInterface.php',
    'CmsGeo\Mapping\SubdivisionInterface'               => __DIR__ . '/src/Mapping/SubdivisionInterface.php',
    'CmsGeo\Module'                                     => __DIR__ . '/src/Module.php',
    'CmsGeo\Mvc\Controller\AdminController'             => __DIR__ . '/src/Mvc/Controller/AdminController.php',
    'CmsGeoTest\Framework\TestCase'                     => __DIR__ . '/tests/Framework/TestCase.php',
    'CmsGeoTest\SampleTest'                             => __DIR__ . '/tests/SampleTest.php',
);
